services:
  task-tracker-db:
    image: postgres
    platform: linux/amd64
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - db-data:/data/postgres
    networks:
      - task-tracker-network

  kafka:
    image: wurstmeister/kafka:latest
    restart: unless-stopped
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "email-sending-tasks:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - task-tracker-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: unless-stopped
    networks:
      - task-tracker-network

  eureka-server-app:
    build:
      context: /opt/task-tracker/eureka-server
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - task-tracker-network

  rest-api-app:
    build:
      context: /opt/task-tracker/rest-api
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      KAFKA_BOOTSTRAP_SERVER_URL: ${KAFKA_BOOTSTRAP_SERVER_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - task-tracker-db
      - kafka
      - eureka-server-app
    networks:
      - task-tracker-network

  user-service-app:
    build:
      context: /opt/task-tracker/user-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - task-tracker-db
      - eureka-server-app
    networks:
      - task-tracker-network

  email-sender-app:
    build:
      context: /opt/task-tracker/email-sender
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      KAFKA_BOOTSTRAP_SERVER_URL: ${KAFKA_BOOTSTRAP_SERVER_URL}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_USERNAME}
    depends_on:
      - kafka
      - eureka-server-app
    networks:
      - task-tracker-network

  report-service-app:
    build:
      context: /opt/task-tracker/report-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      KAFKA_BOOTSTRAP_SERVER_URL: ${KAFKA_BOOTSTRAP_SERVER_URL}
    depends_on:
      - kafka
      - eureka-server-app
      - rest-api-app
    networks:
      - task-tracker-network

volumes:
  db-data:
networks:
  task-tracker-network:
    driver: bridge
